version: "3.18"

services:
  front:
    build:
      dockerfile: docker/Dockerfile
      context: .
    image: koh/frontpage
    container_name: frontpage
    ports:
      - "80:3000"
    networks:
      - sv-network
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 256M
networks:
  sv-network:
    external: true
